config/routes.rb
Rails.application.routes.draw do
  resources :towns
  resources :towns
  resources :students
  get 'welcome/index'
  
  root 'welcome#index'
  

end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, allow_nil: false, presence: true
end

app/models/town.rb
require 'forecast_io'
ForecastIO.configure do |configuration|
  configuration.api_key = '64b1e08c3ffd70590bd6fd0aaaf320ff'
end

class Town < ActiveRecord::Base
  before_validation :geocode_address
  validates :latitude, :longitude, presence: true
  validates :name, allow_nil: false, presence: true
  

  private
    def geocode_address
      place = Nominatim.search(self.name).limit(1).address_details(true)
      if place && place.first
        current_town = place.first
        self.latitude = current_town.lat
        self.longitude = current_town.lon
      end
    end
  
  public
    def get_wheather
      wheather = ForecastIO.forecast(self.latitude, self.longitude, params: { units: 'si' })
      if wheather
        return wheather
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def create
    puts "create!"
    @instance = resource_name.new(resource_params)
    respond_to do |format|
      if @instance.save
        format.html { redirect_to @instance, notice: @instance.class.name+' was successfully created.' }
        format.json { render :show, status: :created, location: @instance }
      else
        format.html { render :new }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @instance = resource
    respond_to do |format|
      if @instance.update(resource_params)
        format.html { redirect_to @instance, notice: @instance.class.name+' was successfully updated.' }
        format.json { render :show, status: :ok, location: @instance }
      else
        format.html { render :edit }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    # Example : Student.find_by_name("toto")
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end
  
  def resource_name
    Student
  end

  def resource_params
    student_params
  end

  def resource
    @student
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :lastname, :birthdate)
    end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: [:show, :edit, :update, :destroy]

  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.all
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
    wheather = @town.get_wheather
    puts wheather.latitude
    puts wheather.currently.temperature
    puts wheather.currently.summary
  end

  # GET /towns/new
  def new
    @town = Town.new
  end

  # GET /towns/1/edit
  def edit
  end
  
  def resource_name
    Town
  end

  def resource_params
    town_params
  end

  def resource
    @town
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town.destroy
    respond_to do |format|
      format.html { redirect_to towns_url, notice: 'Town was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_params
      params.require(:town).permit(:name, :postalcode, :latitude, :longitude)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<div class="create">
  <%= render 'form' %>
</div>

<div class="new">
  <%= link_to 'Show', @student %>
</div>
<br>
<div class="new">
  <%= link_to 'Back', students_path %>
</div>

app/views/students/index.html.erb
<div id="notice">
  <p id="pnotice"><%= notice %></p>
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
</div>

<script>
var $error = $('#pnotice').text();
$( "#notice" ).hide();
if ($error.length === 0) {
    $( "#notice" ).style.display = 'none';
} 
else $( "#notice" ).show();
</script>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr class="table-th">
      <th class="item">Name</th>
      <th class="item">Lastname</th>
      <th class="item">Birthdate</th>
      <th class="item"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr class="table-tr">
        <td class="item"><%= student.name %></td>
        <td class="item"><%= student.lastname %></td>
        <td class="item"><%= student.birthdate %></td>
        <td class="item btns"><%= link_to 'Show', student, class: "btn show-btn" %>
        <%= link_to 'Edit', edit_student_path(student), class: "btn edit-btn"%>
        <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn delete-btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="new">
  <%= link_to 'New Student', new_student_path %>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<div class="create">
  <%= render 'form' %>
</div>


<div class="new">
  <%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<div id="notice">
  <p id="pnotice"><%= notice %></p>
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
</div>

<script>
var $error = $('#pnotice').text();
$( "#notice" ).hide();
if ($error.length === 0) {
    $( "#notice" ).style.display = 'none';
} 
else $( "#notice" ).show();
</script>

<h1>Student details</h1>



<div class="show">
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @student.birthdate %>
</p>
</div>

<div class="new">
  <%= link_to 'Edit', edit_student_path(@student) %>
</div>
<br>
<div class="new">
  <%= link_to 'Back', students_path %>
</div>

app/views/towns/_form.html.erb
<%= form_for(@town) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% @town.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :postalcode %><br>
    <%= f.number_field :postalcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing Town</h1>
<div class="create">
  <%= render 'form' %>
</div>

<div class="new">
  <%= link_to 'Show', @town %>
</div>
<br>
<div class="new">
  <%= link_to 'Back', towns_path %>
</div>

app/views/towns/index.html.erb
<div id="notice">
  <p id="pnotice"><%= notice %></p>
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
</div>

<script>
var $error = $('#pnotice').text();
$( "#notice" ).hide();
if ($error.length === 0) {
    $( "#notice" ).style.display = 'none';
} 
else $( "#notice" ).show();
</script>

<h1>Listing Towns</h1>

<table>
  <thead>
    <tr class="table-th">
      <th class="item-5">Name</th>
      <th class="item-5">Postalcode</th>
      <th class="item-5">Latitude</th>
      <th class="item-5">Longitude</th>
      <th class="item-5"></th>
    </tr>
  </thead>

  <tbody>
    <% @towns.each do |town| %>
      <tr class="table-tr">
        <td class="item-5"><%= town.name %></td>
        <td class="item-5"><%= town.postalcode %></td>
        <td class="item-5"><%= town.latitude %></td>
        <td class="item-5"><%= town.longitude %></td>
        <td class="item-5 btns"><%= link_to 'Show', town, class: "btn show-btn"  %>
        <%= link_to 'Edit', edit_town_path(town), class: "btn edit-btn"  %>
        <%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn delete-btn"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="new">
  <%= link_to 'New Town', new_town_path %>
</div>

app/views/towns/new.html.erb
<h1>New Town</h1>

<div class="create">
  <%= render 'form' %>
</div>

<div class="new">
  <%= link_to 'Back', towns_path %>
</div>

app/views/towns/show.html.erb
<script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script>
var $error = $('#pnotice').text();
$( "#notice" ).hide();
if ($error.length === 0) {
    $( "#notice" ).style.display = 'none';
} 
else $( "#notice" ).show();
</script>

<div id="notice">
  <p id="pnotice"><%= notice %></p>
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
</div>

<h1>Towns details</h1>



<div class="show">
<p>
  <h2>Informations</h2>
</p>
<p>
  <strong>Name:</strong>
  <%= @town.name %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @town.postalcode %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @town.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @town.longitude %>
</p>

<br>
<p>
  <h2>Current wheather</h2>
</p>

<p>
  <strong>Summary:</strong>
  <%= @town.get_wheather.currently.summary %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @town.get_wheather.currently.temperature %> °C
</p>

<br>
<p>
  <h2>Next days</h2>
</p>

<p>
  <strong>Summary:</strong>
  <%= @town.get_wheather.daily.summary %>
</p>

<div class="widget">
<iframe id="forecast_embed" 
        frameborder="0" 
        height="245" 
        width="100%" 
src="//forecast.io/embed/#lat=<%= @town.latitude %>&lon=<%= @town.longitude %>&name=<%= @town.name %>&units=si">
</iframe> 
</div>
 </div>



</div>
  
<div class="new">
<%= link_to 'Edit', edit_town_path(@town) %>
</div>
<br>
<div class="new">
<%= link_to 'Back', towns_path %>
</div>

app/views/welcome/index.html.erb
<h1 class="home">Welcome</h1>
<div class="new go">
  <%= link_to "Students", students_path %>
</div>
<br>
<div class="new go">
  <%= link_to "Towns", towns_path %>
</div>